spring.application.name=restart
server.port=4000

spring.datasource.url=jdbc:mysql://172.26.118.96/restart?serverTimezone=UTC&characterEncoding=UTF-8
spring.datasource.username=restart
spring.datasource.password=re5060!!
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=110MB